### ISSUE TITLE
Add Tags for Release Versions

### ISSUE THREAD

**Issue by asayler** [ndunand/moodle-qbehaviour_regexpadaptivewithhelp#1]
Would it be possible to tag the release versions of this repo in git? This makes it much simpler to clone a specific version of the repo and eases the burden of downstream release management, especially for those of us building Moodle installs via scripts (e.g. for Docker).

E.g.
Running:

```
git tag 2016071400 5cfcbc2b6868ce1768cedc3c298e1e1998165e35
git push --tags
```

Allows one to replace:

```
git clone --recursive --single-branch \
"https://github.com/ndunand/moodle-qbehaviour_regexpadaptivewithhelp.git" \
"${MOODLE_CODE_PATH}/question/behaviour/regexpadaptivewithhelp" \
&& cd "${MOODLE_CODE_PATH}/question/behaviour/regexpadaptivewithhelp" \
&& git checkout 5cfcbc2b6868ce1768cedc3c298e1e1998165e35 \
&& cd
```

With the cleaner:

```
git clone --recursive --single-branch -b 2016071400 \
"https://github.com/ndunand/moodle-qbehaviour_regexpadaptivewithhelp.git" \
"${MOODLE_CODE_PATH}/question/behaviour/regexpadaptivewithhelp"
```

I'd file this as a pull quest, but github does not currently allow importing git metadata such as tags via pull request -- tags can only be applied by someone with commit access to the repo itself.

**Comment by ndunand** [comment]
Okay, done
